# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.BaseFinetuning.html

# Finetunes a flow matching model for auxiliary tasks.
# Look at the above link for more detailed information regarding the base implementation.
auxiliary_task_finetuning:
  _target_: zatom.callbacks.finetuning.FlowMatchingAuxiliaryTaskFinetuning
  # Time range inspired by https://arxiv.org/abs/2502.07001
  t_min: 0.98
  t_max: 1.0
