defaults:
  - ema_weight_averaging
  - last_model_checkpoint
  - model_checkpoint
  - model_summary
  - _self_

last_model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  verbose: True
  every_n_train_steps: 5000

model_summary:
  max_depth: -1
