defaults:
  - auxiliary_task_finetuning
  - last_model_checkpoint
  - learning_rate_monitor
  - model_checkpoint
  - model_summary
  - _self_

last_model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  verbose: True
  every_n_train_steps: 5000

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "model-epoch@{epoch}-step@{step}-val_qm9_property_loss@{val_qm9/aux_global_property_loss:.4f}-val_omol25_energy_loss@{val_omol25/aux_global_energy_loss:.4f}"
  monitor: "val_qm9/aux_global_property_loss"
  mode: "max"
  save_last: True

model_summary:
  max_depth: -1
