defaults:
  # - early_stopping
  - ema_weight_averaging
  - last_model_checkpoint
  # - learning_rate_monitor
  - model_checkpoint
  - model_summary
  - _self_

# early_stopping:
#   monitor: "val/valid_rate"
#   patience: 100
#   mode: "max"

last_model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  verbose: True
  every_n_train_steps: 5000

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "ebm-epoch@{epoch}-step@{step}-val_geom_valid_rate@{val_geom/valid_rate:.4f}"
  monitor: "val_geom/valid_rate"
  mode: "max"
  save_last: True

model_summary:
  max_depth: -1
