# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.WeightAveraging.html

# Maintains an average of model weights.
# Look at the above link for more detailed information regarding the original implementation.
ema_weight_averaging:
  _target_: lightning.pytorch.callbacks.weight_averaging.EMAWeightAveraging
  device: null
  use_buffers: false # NOTE: this should be `true` if one is using BatchNorm layers
  decay: 0.999
  update_every_n_steps: 1
  update_starting_at_step: null
  update_starting_at_epoch: null
