defaults:
  - ema_weight_averaging
  - last_model_checkpoint
  - model_checkpoint
  - model_summary
  - _self_

last_model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  verbose: True
  every_n_train_steps: 5000

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "fm-epoch@{epoch}-step@{step}-val_qm9_valid_rate@{val_qm9/valid_rate:.4f}-val_mp20_valid_rate@{val_mp20/valid_rate:.4f}"
  monitor: "val_mp20/valid_rate"
  mode: "max"
  save_last: True

model_summary:
  max_depth: -1
