# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.WeightAveraging.html

# Maintains an average of model weights.
# Look at the above link for more detailed information regarding the original implementation.
weight_averaging:
  _target_: lightning.pytorch.callbacks.weight_averaging.WeightAveraging
  device: null
  use_buffers: false # NOTE: this should be `true` if one is using BatchNorm layers
