# @package _global_

defaults:
  - _self_
  - data: joint # NOTE: must be one of (`joint`, `qm9_only`, `mp20_only`, `qmof150_only`, `omol25_only`, `geom_only`)
  - encoder: transformer # NOTE: must be one of (`transformer`)
  - ecoder: ebt # NOTE: must be one of (`ebt`, `mft`)
  - ebm_module: ebm
  - logger: null
  - strategy: default
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - environment: default

# run name and date, e.g., for logging
name: ""
date: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# task name, determines output directory path
task_name: "eval_ebm"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train_ebm.py tags="[first_tag, second_tag]"`
tags: ["joint", "ebm", "eval"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ""

# seed for random number generators in pytorch, numpy and python.random
seed: 42

# precision for PyTorch's floating-point matrix multiplication
float32_matmul_precision: highest # NOTE: must be one of (`medium`, `high`, `highest`)
