# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: joint # NOTE: must be one of (`joint`, `qm9_only`, `mp20_only`, `qmof150_only`, `omol25_only`, `geom_only`)
  - encoder: transformer # NOTE: must be one of (`transformer`)
  - ecoder: ebt # NOTE: must be one of (`ebt`, `mft`)
  - ebm_module: ebm
  - callbacks: ebm_default # NOTE: must be one of `ebm_{default,qm9_only,mp20_only,qmof150_only,omol25_only,geom_only}`
  - logger: null # set logger here or use command line (e.g. `python train_ebm.py logger=tensorboard`)
  - strategy: default
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - environment: default

# run name and date, e.g., for logging
name: ""
date: ${now:%Y-%m-%d}_${now:%H-%M-%S}

# task name, determines output directory path
task_name: "train_ebm"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train_ebm.py tags="[first_tag, second_tag]"`
tags: ["joint", "ebm", "train"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: null
resume_from_last_step_dir: True # if `True`, resume from the last (i.e., max '{epoch}-{step}') checkpoint in the specified directory

# seed for random number generators in pytorch, numpy and python.random
seed: ${generate_index:8}

# precision for PyTorch's floating-point matrix multiplication
float32_matmul_precision: highest # NOTE: must be one of (`medium`, `high`, `highest`)
